services:
  server:
    build: .
    volumes:
      - /media/storage:/data
    env_file:
      - env/web.env

  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - env/tunnel.env

